name: Publish Packages

on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build Portable
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish Portable
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: Ash.Portable/Ash.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}

    - name: Publish Content
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: Ash.Content/Ash.Content.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
          
    - name: Publish DefaultEC
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: Ash.DefaultEC/Ash.DefaultEC.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
          
    - name: Publish Gia
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: Ash.Gia/Ash.Gia.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}